// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.4
// source: game.proto

package plr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求房间列表
type C3000001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameKindID    int32                  `protobuf:"varint,1,opt,name=GameKindID,proto3" json:"GameKindID,omitempty"` // 游戏类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C3000001) Reset() {
	*x = C3000001{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C3000001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C3000001) ProtoMessage() {}

func (x *C3000001) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C3000001.ProtoReflect.Descriptor instead.
func (*C3000001) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *C3000001) GetGameKindID() int32 {
	if x != nil {
		return x.GameKindID
	}
	return 0
}

type S3000001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"` // 状态码
	Rooms         []*S3000001_RoomInfo   `protobuf:"bytes,2,rep,name=Rooms,proto3" json:"Rooms,omitempty"`      // 房间列表信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3000001) Reset() {
	*x = S3000001{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3000001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3000001) ProtoMessage() {}

func (x *S3000001) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3000001.ProtoReflect.Descriptor instead.
func (*S3000001) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *S3000001) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S3000001) GetRooms() []*S3000001_RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 请求匹配
type C3000002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameKindID    int32                  `protobuf:"varint,1,opt,name=GameKindID,proto3" json:"GameKindID,omitempty"` // 游戏类型
	RoomID        int32                  `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`         // 房间ID
	UserID        string                 `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`          // 玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C3000002) Reset() {
	*x = C3000002{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C3000002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C3000002) ProtoMessage() {}

func (x *C3000002) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C3000002.ProtoReflect.Descriptor instead.
func (*C3000002) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *C3000002) GetGameKindID() int32 {
	if x != nil {
		return x.GameKindID
	}
	return 0
}

func (x *C3000002) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *C3000002) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type S3000002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"` // 状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3000002) Reset() {
	*x = S3000002{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3000002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3000002) ProtoMessage() {}

func (x *S3000002) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3000002.ProtoReflect.Descriptor instead.
func (*S3000002) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *S3000002) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

type S3000001_RoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomID         int32                  `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`                  // 房间ID
	BaseAmount     float64                `protobuf:"fixed64,2,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`         // 底分
	MinEnterAmount float64                `protobuf:"fixed64,3,opt,name=MinEnterAmount,proto3" json:"MinEnterAmount,omitempty"` // 最低进入额度
	MaxEnterAmount float64                `protobuf:"fixed64,4,opt,name=MaxEnterAmount,proto3" json:"MaxEnterAmount,omitempty"` // 最大进入额度
	RoomName       string                 `protobuf:"bytes,5,opt,name=RoomName,proto3" json:"RoomName,omitempty"`               // 房间名称
	MinRatio       float64                `protobuf:"fixed64,6,opt,name=MinRatio,proto3" json:"MinRatio,omitempty"`
	MaxRatio       float64                `protobuf:"fixed64,7,opt,name=MaxRatio,proto3" json:"MaxRatio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S3000001_RoomInfo) Reset() {
	*x = S3000001_RoomInfo{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3000001_RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3000001_RoomInfo) ProtoMessage() {}

func (x *S3000001_RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3000001_RoomInfo.ProtoReflect.Descriptor instead.
func (*S3000001_RoomInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0}
}

func (x *S3000001_RoomInfo) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *S3000001_RoomInfo) GetBaseAmount() float64 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *S3000001_RoomInfo) GetMinEnterAmount() float64 {
	if x != nil {
		return x.MinEnterAmount
	}
	return 0
}

func (x *S3000001_RoomInfo) GetMaxEnterAmount() float64 {
	if x != nil {
		return x.MaxEnterAmount
	}
	return 0
}

func (x *S3000001_RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *S3000001_RoomInfo) GetMinRatio() float64 {
	if x != nil {
		return x.MinRatio
	}
	return 0
}

func (x *S3000001_RoomInfo) GetMaxRatio() float64 {
	if x != nil {
		return x.MaxRatio
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\"*\n" +
	"\bC3000001\x12\x1e\n" +
	"\n" +
	"GameKindID\x18\x01 \x01(\x05R\n" +
	"GameKindID\"\xb7\x02\n" +
	"\bS3000001\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCode\x12(\n" +
	"\x05Rooms\x18\x02 \x03(\v2\x12.S3000001.RoomInfoR\x05Rooms\x1a\xe6\x01\n" +
	"\bRoomInfo\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\x05R\x06RoomID\x12\x1e\n" +
	"\n" +
	"BaseAmount\x18\x02 \x01(\x01R\n" +
	"BaseAmount\x12&\n" +
	"\x0eMinEnterAmount\x18\x03 \x01(\x01R\x0eMinEnterAmount\x12&\n" +
	"\x0eMaxEnterAmount\x18\x04 \x01(\x01R\x0eMaxEnterAmount\x12\x1a\n" +
	"\bRoomName\x18\x05 \x01(\tR\bRoomName\x12\x1a\n" +
	"\bMinRatio\x18\x06 \x01(\x01R\bMinRatio\x12\x1a\n" +
	"\bMaxRatio\x18\a \x01(\x01R\bMaxRatio\"Z\n" +
	"\bC3000002\x12\x1e\n" +
	"\n" +
	"GameKindID\x18\x01 \x01(\x05R\n" +
	"GameKindID\x12\x16\n" +
	"\x06RoomID\x18\x02 \x01(\x05R\x06RoomID\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\tR\x06UserID\"$\n" +
	"\bS3000002\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCodeB\aZ\x05./plrb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_proto_goTypes = []any{
	(*C3000001)(nil),          // 0: C3000001
	(*S3000001)(nil),          // 1: S3000001
	(*C3000002)(nil),          // 2: C3000002
	(*S3000002)(nil),          // 3: S3000002
	(*S3000001_RoomInfo)(nil), // 4: S3000001.RoomInfo
}
var file_game_proto_depIdxs = []int32{
	4, // 0: S3000001.Rooms:type_name -> S3000001.RoomInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
