// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.4
// source: system.proto

package plr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取用户信息
type C0000003 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"` //用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C0000003) Reset() {
	*x = C0000003{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C0000003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C0000003) ProtoMessage() {}

func (x *C0000003) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C0000003.ProtoReflect.Descriptor instead.
func (*C0000003) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *C0000003) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// 返回用户信息
type S0000003 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Wealth        float64                `protobuf:"fixed64,4,opt,name=Wealth,proto3" json:"Wealth,omitempty"`
	FaceID        int32                  `protobuf:"varint,5,opt,name=FaceID,proto3" json:"FaceID,omitempty"`
	Sexuality     int32                  `protobuf:"varint,6,opt,name=Sexuality,proto3" json:"Sexuality,omitempty"`
	IPArea        string                 `protobuf:"bytes,7,opt,name=IPArea,proto3" json:"IPArea,omitempty"`
	AccType       int32                  `protobuf:"varint,8,opt,name=AccType,proto3" json:"AccType,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty"` //1：游戏中 下面字段生效
	KindID        int32                  `protobuf:"varint,10,opt,name=KindID,proto3" json:"KindID,omitempty"`
	RoomID        int32                  `protobuf:"varint,11,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	TableID       int32                  `protobuf:"varint,12,opt,name=TableID,proto3" json:"TableID,omitempty"`
	SeatNo        int32                  `protobuf:"varint,13,opt,name=SeatNo,proto3" json:"SeatNo,omitempty"`
	RoundName     string                 `protobuf:"bytes,14,opt,name=RoundName,proto3" json:"RoundName,omitempty"`
	VipLevel      int32                  `protobuf:"varint,15,opt,name=VipLevel,proto3" json:"VipLevel,omitempty"`       //vip等级
	FaceFrameID   int32                  `protobuf:"varint,16,opt,name=FaceFrameID,proto3" json:"FaceFrameID,omitempty"` //头像框ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S0000003) Reset() {
	*x = S0000003{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S0000003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S0000003) ProtoMessage() {}

func (x *S0000003) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S0000003.ProtoReflect.Descriptor instead.
func (*S0000003) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *S0000003) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S0000003) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *S0000003) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *S0000003) GetWealth() float64 {
	if x != nil {
		return x.Wealth
	}
	return 0
}

func (x *S0000003) GetFaceID() int32 {
	if x != nil {
		return x.FaceID
	}
	return 0
}

func (x *S0000003) GetSexuality() int32 {
	if x != nil {
		return x.Sexuality
	}
	return 0
}

func (x *S0000003) GetIPArea() string {
	if x != nil {
		return x.IPArea
	}
	return ""
}

func (x *S0000003) GetAccType() int32 {
	if x != nil {
		return x.AccType
	}
	return 0
}

func (x *S0000003) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *S0000003) GetKindID() int32 {
	if x != nil {
		return x.KindID
	}
	return 0
}

func (x *S0000003) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *S0000003) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *S0000003) GetSeatNo() int32 {
	if x != nil {
		return x.SeatNo
	}
	return 0
}

func (x *S0000003) GetRoundName() string {
	if x != nil {
		return x.RoundName
	}
	return ""
}

func (x *S0000003) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *S0000003) GetFaceFrameID() int32 {
	if x != nil {
		return x.FaceFrameID
	}
	return 0
}

// Token 登陆
type C0000018 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	MachineID     string                 `protobuf:"bytes,3,opt,name=MachineID,proto3" json:"MachineID,omitempty"`    //机器唯一标识码
	PlatFormID    int32                  `protobuf:"varint,4,opt,name=PlatFormID,proto3" json:"PlatFormID,omitempty"` //平台ID
	IPAddr        string                 `protobuf:"bytes,5,opt,name=IPAddr,proto3" json:"IPAddr,omitempty"`
	TerminalType  int32                  `protobuf:"varint,6,opt,name=TerminalType,proto3" json:"TerminalType,omitempty"` //1:IOS,2:Andriod 3:Other
	ClientVersion string                 `protobuf:"bytes,7,opt,name=ClientVersion,proto3" json:"ClientVersion,omitempty"`
	GameID        int32                  `protobuf:"varint,8,opt,name=GameID,proto3" json:"GameID,omitempty"`   //游戏ID
	Model         string                 `protobuf:"bytes,9,opt,name=Model,proto3" json:"Model,omitempty"`      //机型
	Version       string                 `protobuf:"bytes,10,opt,name=Version,proto3" json:"Version,omitempty"` //系统版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C0000018) Reset() {
	*x = C0000018{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C0000018) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C0000018) ProtoMessage() {}

func (x *C0000018) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C0000018.ProtoReflect.Descriptor instead.
func (*C0000018) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *C0000018) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *C0000018) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C0000018) GetMachineID() string {
	if x != nil {
		return x.MachineID
	}
	return ""
}

func (x *C0000018) GetPlatFormID() int32 {
	if x != nil {
		return x.PlatFormID
	}
	return 0
}

func (x *C0000018) GetIPAddr() string {
	if x != nil {
		return x.IPAddr
	}
	return ""
}

func (x *C0000018) GetTerminalType() int32 {
	if x != nil {
		return x.TerminalType
	}
	return 0
}

func (x *C0000018) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *C0000018) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *C0000018) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *C0000018) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type S0000018 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`     //返回码
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`        //id
	HeatTimes     int32                  `protobuf:"varint,3,opt,name=HeatTimes,proto3" json:"HeatTimes,omitempty"` //心跳时间
	Token         string                 `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`          //刷新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S0000018) Reset() {
	*x = S0000018{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S0000018) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S0000018) ProtoMessage() {}

func (x *S0000018) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S0000018.ProtoReflect.Descriptor instead.
func (*S0000018) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *S0000018) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S0000018) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *S0000018) GetHeatTimes() int32 {
	if x != nil {
		return x.HeatTimes
	}
	return 0
}

func (x *S0000018) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 踢玩家下线
type P1000008 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"` // 0:被系统踢出 1：异机登陆
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P1000008) Reset() {
	*x = P1000008{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P1000008) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P1000008) ProtoMessage() {}

func (x *P1000008) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P1000008.ProtoReflect.Descriptor instead.
func (*P1000008) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *P1000008) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *P1000008) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 服务状态变更
type P1000009 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"` // 1:停服
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P1000009) Reset() {
	*x = P1000009{}
	mi := &file_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P1000009) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P1000009) ProtoMessage() {}

func (x *P1000009) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P1000009.ProtoReflect.Descriptor instead.
func (*P1000009) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{5}
}

func (x *P1000009) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户入座
type N0000001 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RoomID        int32                  `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	TableID       int32                  `protobuf:"varint,3,opt,name=TableID,proto3" json:"TableID,omitempty"`
	SeatNo        int32                  `protobuf:"varint,4,opt,name=SeatNo,proto3" json:"SeatNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000001) Reset() {
	*x = N0000001{}
	mi := &file_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000001) ProtoMessage() {}

func (x *N0000001) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000001.ProtoReflect.Descriptor instead.
func (*N0000001) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{6}
}

func (x *N0000001) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *N0000001) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *N0000001) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *N0000001) GetSeatNo() int32 {
	if x != nil {
		return x.SeatNo
	}
	return 0
}

// 用户离座
type N0000002 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000002) Reset() {
	*x = N0000002{}
	mi := &file_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000002) ProtoMessage() {}

func (x *N0000002) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000002.ProtoReflect.Descriptor instead.
func (*N0000002) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{7}
}

func (x *N0000002) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// 开始牌局
type N0000003 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableID       int32                  `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
	RoundName     string                 `protobuf:"bytes,2,opt,name=RoundName,proto3" json:"RoundName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000003) Reset() {
	*x = N0000003{}
	mi := &file_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000003) ProtoMessage() {}

func (x *N0000003) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000003.ProtoReflect.Descriptor instead.
func (*N0000003) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{8}
}

func (x *N0000003) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *N0000003) GetRoundName() string {
	if x != nil {
		return x.RoundName
	}
	return ""
}

// 结束牌局
type N0000004 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundName     string                 `protobuf:"bytes,1,opt,name=RoundName,proto3" json:"RoundName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000004) Reset() {
	*x = N0000004{}
	mi := &file_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000004) ProtoMessage() {}

func (x *N0000004) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000004.ProtoReflect.Descriptor instead.
func (*N0000004) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{9}
}

func (x *N0000004) GetRoundName() string {
	if x != nil {
		return x.RoundName
	}
	return ""
}

// 用户离线
type N0000005 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000005) Reset() {
	*x = N0000005{}
	mi := &file_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000005) ProtoMessage() {}

func (x *N0000005) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000005.ProtoReflect.Descriptor instead.
func (*N0000005) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{10}
}

func (x *N0000005) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type N0000006 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RoomID        int32                  `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	TableID       int32                  `protobuf:"varint,3,opt,name=TableID,proto3" json:"TableID,omitempty"`
	SeatNo        int32                  `protobuf:"varint,4,opt,name=SeatNo,proto3" json:"SeatNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000006) Reset() {
	*x = N0000006{}
	mi := &file_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000006) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000006) ProtoMessage() {}

func (x *N0000006) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000006.ProtoReflect.Descriptor instead.
func (*N0000006) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{11}
}

func (x *N0000006) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *N0000006) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *N0000006) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *N0000006) GetSeatNo() int32 {
	if x != nil {
		return x.SeatNo
	}
	return 0
}

type N0000007 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *N0000007) Reset() {
	*x = N0000007{}
	mi := &file_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N0000007) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N0000007) ProtoMessage() {}

func (x *N0000007) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N0000007.ProtoReflect.Descriptor instead.
func (*N0000007) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{12}
}

func (x *N0000007) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// 获取服务器维护状态
type C0000031 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C0000031) Reset() {
	*x = C0000031{}
	mi := &file_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C0000031) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C0000031) ProtoMessage() {}

func (x *C0000031) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C0000031.ProtoReflect.Descriptor instead.
func (*C0000031) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{13}
}

type S0000031 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetCode        int32                  `protobuf:"varint,1,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
	ServerState    int32                  `protobuf:"varint,2,opt,name=ServerState,proto3" json:"ServerState,omitempty"`       //1:停服 2:测试 3:开服
	ServerStopTime int64                  `protobuf:"varint,3,opt,name=ServerStopTime,proto3" json:"ServerStopTime,omitempty"` //停服维护时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S0000031) Reset() {
	*x = S0000031{}
	mi := &file_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S0000031) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S0000031) ProtoMessage() {}

func (x *S0000031) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S0000031.ProtoReflect.Descriptor instead.
func (*S0000031) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{14}
}

func (x *S0000031) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S0000031) GetServerState() int32 {
	if x != nil {
		return x.ServerState
	}
	return 0
}

func (x *S0000031) GetServerStopTime() int64 {
	if x != nil {
		return x.ServerStopTime
	}
	return 0
}

// 设置停服时间
type P1000010 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerStopTime int64                  `protobuf:"varint,1,opt,name=ServerStopTime,proto3" json:"ServerStopTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *P1000010) Reset() {
	*x = P1000010{}
	mi := &file_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P1000010) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P1000010) ProtoMessage() {}

func (x *P1000010) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P1000010.ProtoReflect.Descriptor instead.
func (*P1000010) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{15}
}

func (x *P1000010) GetServerStopTime() int64 {
	if x != nil {
		return x.ServerStopTime
	}
	return 0
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\"\"\n" +
	"\bC0000003\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"\xae\x03\n" +
	"\bS0000003\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCode\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12\x16\n" +
	"\x06Wealth\x18\x04 \x01(\x01R\x06Wealth\x12\x16\n" +
	"\x06FaceID\x18\x05 \x01(\x05R\x06FaceID\x12\x1c\n" +
	"\tSexuality\x18\x06 \x01(\x05R\tSexuality\x12\x16\n" +
	"\x06IPArea\x18\a \x01(\tR\x06IPArea\x12\x18\n" +
	"\aAccType\x18\b \x01(\x05R\aAccType\x12\x16\n" +
	"\x06Status\x18\t \x01(\x05R\x06Status\x12\x16\n" +
	"\x06KindID\x18\n" +
	" \x01(\x05R\x06KindID\x12\x16\n" +
	"\x06RoomID\x18\v \x01(\x05R\x06RoomID\x12\x18\n" +
	"\aTableID\x18\f \x01(\x05R\aTableID\x12\x16\n" +
	"\x06SeatNo\x18\r \x01(\x05R\x06SeatNo\x12\x1c\n" +
	"\tRoundName\x18\x0e \x01(\tR\tRoundName\x12\x1a\n" +
	"\bVipLevel\x18\x0f \x01(\x05R\bVipLevel\x12 \n" +
	"\vFaceFrameID\x18\x10 \x01(\x05R\vFaceFrameID\"\xaa\x02\n" +
	"\bC0000018\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\x12\x1c\n" +
	"\tMachineID\x18\x03 \x01(\tR\tMachineID\x12\x1e\n" +
	"\n" +
	"PlatFormID\x18\x04 \x01(\x05R\n" +
	"PlatFormID\x12\x16\n" +
	"\x06IPAddr\x18\x05 \x01(\tR\x06IPAddr\x12\"\n" +
	"\fTerminalType\x18\x06 \x01(\x05R\fTerminalType\x12$\n" +
	"\rClientVersion\x18\a \x01(\tR\rClientVersion\x12\x16\n" +
	"\x06GameID\x18\b \x01(\x05R\x06GameID\x12\x14\n" +
	"\x05Model\x18\t \x01(\tR\x05Model\x12\x18\n" +
	"\aVersion\x18\n" +
	" \x01(\tR\aVersion\"p\n" +
	"\bS0000018\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCode\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x1c\n" +
	"\tHeatTimes\x18\x03 \x01(\x05R\tHeatTimes\x12\x14\n" +
	"\x05Token\x18\x04 \x01(\tR\x05Token\"6\n" +
	"\bP1000008\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\"\"\n" +
	"\bP1000009\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\"l\n" +
	"\bN0000001\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x16\n" +
	"\x06RoomID\x18\x02 \x01(\x05R\x06RoomID\x12\x18\n" +
	"\aTableID\x18\x03 \x01(\x05R\aTableID\x12\x16\n" +
	"\x06SeatNo\x18\x04 \x01(\x05R\x06SeatNo\"\"\n" +
	"\bN0000002\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"B\n" +
	"\bN0000003\x12\x18\n" +
	"\aTableID\x18\x01 \x01(\x05R\aTableID\x12\x1c\n" +
	"\tRoundName\x18\x02 \x01(\tR\tRoundName\"(\n" +
	"\bN0000004\x12\x1c\n" +
	"\tRoundName\x18\x01 \x01(\tR\tRoundName\"\"\n" +
	"\bN0000005\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"l\n" +
	"\bN0000006\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x16\n" +
	"\x06RoomID\x18\x02 \x01(\x05R\x06RoomID\x12\x18\n" +
	"\aTableID\x18\x03 \x01(\x05R\aTableID\x12\x16\n" +
	"\x06SeatNo\x18\x04 \x01(\x05R\x06SeatNo\"\"\n" +
	"\bN0000007\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"\n" +
	"\n" +
	"\bC0000031\"n\n" +
	"\bS0000031\x12\x18\n" +
	"\aRetCode\x18\x01 \x01(\x05R\aRetCode\x12 \n" +
	"\vServerState\x18\x02 \x01(\x05R\vServerState\x12&\n" +
	"\x0eServerStopTime\x18\x03 \x01(\x03R\x0eServerStopTime\"2\n" +
	"\bP1000010\x12&\n" +
	"\x0eServerStopTime\x18\x01 \x01(\x03R\x0eServerStopTimeB\aZ\x05./plrb\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_system_proto_goTypes = []any{
	(*C0000003)(nil), // 0: C0000003
	(*S0000003)(nil), // 1: S0000003
	(*C0000018)(nil), // 2: C0000018
	(*S0000018)(nil), // 3: S0000018
	(*P1000008)(nil), // 4: P1000008
	(*P1000009)(nil), // 5: P1000009
	(*N0000001)(nil), // 6: N0000001
	(*N0000002)(nil), // 7: N0000002
	(*N0000003)(nil), // 8: N0000003
	(*N0000004)(nil), // 9: N0000004
	(*N0000005)(nil), // 10: N0000005
	(*N0000006)(nil), // 11: N0000006
	(*N0000007)(nil), // 12: N0000007
	(*C0000031)(nil), // 13: C0000031
	(*S0000031)(nil), // 14: S0000031
	(*P1000010)(nil), // 15: P1000010
}
var file_system_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
